name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set Authority
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "%%authority%%"
          replace: ${{ secrets.SSO_AUTHORITY }}
          regex: false

      - name: Set Authority
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "%%client_id%%"
          replace: ${{ secrets.CLIENT_ID }}
          regex: false

      - name: Set Authority
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "%%client_secret%%"
          replace: ${{ secrets.CLIENT_SECRET }}
          regex: false

      - name: Set Authority
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "%%redirect_url%%"
          replace: ${{ secrets.REDIRECT_URL }}
          regex: false

      - name: Set Authority
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "%%db_host%%"
          replace: ${{ secrets.DB_HOST }}
          regex: false

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: "temurin"

      - name: Build application
        run: |
          ./gradlew bundleReact
          ./gradlew bundleApp

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: alban098/finance:latest
          labels: ${{ steps.meta.outputs.labels }}